### ISSUE TITLE
About the Proof of Theorem 2.1

### ISSUE THREAD

**Issue by lilybud** [PurdueMINDS/RelationalPooling#1]
![image](https://user-images.githubusercontent.com/32999087/86125819-dd4dfa00-bb0f-11ea-94c2-12441d90f8a2.png)
this is my question.
sorry， i have few idea about the inference proccess.  
so i hope my question is not bothering you. thank you~

**Comment by rmurphy2718** [comment]
@lilybud , thank you for your interest in our paper!  You are correct, and that's a mistake.  The 1/V! should not be there.
