### ISSUE TITLE
About proof of Theorem 2.1

### ISSUE THREAD

**Issue by ThyrixYang** [PurdueMINDS/RelationalPooling#2]
Hi,

Thanks for your impressive contribution to the machine learning community!
I'm trying to understand your proofs in the appendix but encountered some difficulty.

In the Proof of Theorem 2.1, I understand that the universal approximation theorem guarantees distinct encodings of distinct inputs. However, I think it's not the case that the average of these encodings will still be distinct. For example, 2+3+7=1+5+6. Thus a universal powerful network may still not be able to solve the "most general classification task". And it's clear that distinct encoding is not necessary. So I'm confused about the concept of "most expressive representation of G", which seems to be a perfect isomorphic tester (given a universal approximator).
Thanks for your time!

**Comment by rmurphy2718** [comment]
Hello,

Thanks for your interest.  I am a little busy at the moment and will attempt to answer quickly but cannot look into it in detail.  My apologies.

* We are indeed claiming the ability to distinguish nonisomorphic graphs.  There is nothing wrong or surprising about this claim as we are not claiming to do it efficiently; full RP, without approximations, has combinatorial time complexity.  
* ""Distinct encoding is not necessary": There may be more elegant proofs than the sketch we provided here.  A distinct encoding is sufficient for our purposes however.
* The latent representation of the graphs is extremely high dimensional, which upon reflection will help you see that the average is distinct.  (If it helps, also take the sum: without loss of generality we can let \harrow{f} include the normalization factor n!).  Think like this.  Intuitively speaking, every distinct graph gets its own one-hot encoding vector (this is where we need to leverage our finite-feature assumptions stated in the paper).  Notice that different graphs in the same isomorphism family will get different one-hot encodings.  After summation, all the bits for that family will be turned on.  None of the other bits for any other family will be.  Then the downstream layer can map that into a distinct prediction for every isomorphism family.

Hope this helps.

## Other comments
* There is a work by Sato with augmented features, they add some insight and claim that their construction generalizes our proof of universality.  You could also have a look at that.
* There's also work on randomized features with more general results.

**Comment by ThyrixYang** [comment]
Thanks for your kind and detailed explanation!
